import { Restaurant, Booking, Review, TimeSlot } from './types';

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: 'El Corazon',
    cuisine: 'Mexican',
    description: 'Authentic Mexican cuisine with a modern twist. Experience the vibrant flavors of Mexico in an elegant setting.',
    address: '123 Main Street, New York, NY 10001',
    phone: '+1 (212) 555-0101',
    email: 'info@elcorazon.com',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    rating: 4.7,
    reviewCount: 234,
    priceRange: '$$',
    openingHours: '12:00 PM - 10:00 PM',
    tables: [
      { id: 't1', name: 'Window Table 1', location: 'Window', capacity: 2 },
      { id: 't2', name: 'Window Table 2', location: 'Window', capacity: 4 },
      { id: 't3', name: 'Patio Table 1', location: 'Patio', capacity: 6 },
      { id: 't4', name: 'Bar Table 1', location: 'Bar', capacity: 2 },
      { id: 't5', name: 'Main Floor Table 1', location: 'Main Floor', capacity: 4 },
      { id: 't6', name: 'Main Floor Table 2', location: 'Main Floor', capacity: 8 },
    ],
  },
  {
    id: '2',
    name: 'Sakura Garden',
    cuisine: 'Japanese',
    description: 'Traditional Japanese dining experience featuring fresh sushi, ramen, and seasonal omakase menus.',
    address: '456 Park Avenue, New York, NY 10022',
    phone: '+1 (212) 555-0202',
    email: 'info@sakuragarden.com',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    rating: 4.9,
    reviewCount: 456,
    priceRange: '$$$',
    openingHours: '11:30 AM - 11:00 PM',
    tables: [
      { id: 't7', name: 'Tatami Room 1', location: 'Tatami Room', capacity: 4 },
      { id: 't8', name: 'Tatami Room 2', location: 'Tatami Room', capacity: 6 },
      { id: 't9', name: 'Sushi Bar 1', location: 'Sushi Bar', capacity: 2 },
      { id: 't10', name: 'Main Hall Table 1', location: 'Main Hall', capacity: 4 },
      { id: 't11', name: 'Main Hall Table 2', location: 'Main Hall', capacity: 8 },
    ],
  },
  {
    id: '3',
    name: 'La Bella Italia',
    cuisine: 'Italian',
    description: 'Classic Italian trattoria serving handmade pasta, wood-fired pizzas, and fine Italian wines.',
    address: '789 Broadway, New York, NY 10003',
    phone: '+1 (212) 555-0303',
    email: 'info@labellaita.com',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    rating: 4.5,
    reviewCount: 312,
    priceRange: '$$',
    openingHours: '12:00 PM - 11:00 PM',
    tables: [
      { id: 't12', name: 'Garden Patio 1', location: 'Garden Patio', capacity: 4 },
      { id: 't13', name: 'Garden Patio 2', location: 'Garden Patio', capacity: 6 },
      { id: 't14', name: 'Indoor Table 1', location: 'Indoor', capacity: 2 },
      { id: 't15', name: 'Indoor Table 2', location: 'Indoor', capacity: 4 },
      { id: 't16', name: 'Private Room', location: 'Private Room', capacity: 10 },
    ],
  },
  {
    id: '4',
    name: 'The Spice Route',
    cuisine: 'Indian',
    description: 'A culinary journey through India featuring aromatic curries, tandoor specialties, and craft cocktails.',
    address: '321 Lexington Ave, New York, NY 10016',
    phone: '+1 (212) 555-0404',
    email: 'info@spiceroute.com',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    rating: 4.6,
    reviewCount: 189,
    priceRange: '$$',
    openingHours: '12:00 PM - 10:30 PM',
    tables: [
      { id: 't17', name: 'Lounge Table 1', location: 'Lounge', capacity: 2 },
      { id: 't18', name: 'Lounge Table 2', location: 'Lounge', capacity: 4 },
      { id: 't19', name: 'Main Dining 1', location: 'Main Dining', capacity: 4 },
      { id: 't20', name: 'Main Dining 2', location: 'Main Dining', capacity: 6 },
    ],
  },
  {
    id: '5',
    name: 'Maison Bordeaux',
    cuisine: 'French',
    description: 'Elegant French cuisine featuring classic bistro dishes, fine wines, and an intimate Parisian atmosphere.',
    address: '654 Fifth Avenue, New York, NY 10019',
    phone: '+1 (212) 555-0505',
    email: 'info@maisonbordeaux.com',
    image: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80',
    rating: 4.8,
    reviewCount: 567,
    priceRange: '$$$$',
    openingHours: '12:00 PM - 11:00 PM',
    tables: [
      { id: 't21', name: 'Terrace Table 1', location: 'Terrace', capacity: 2 },
      { id: 't22', name: 'Terrace Table 2', location: 'Terrace', capacity: 4 },
      { id: 't23', name: 'Wine Cellar Table', location: 'Wine Cellar', capacity: 6 },
      { id: 't24', name: 'Main Salon 1', location: 'Main Salon', capacity: 4 },
      { id: 't25', name: 'Main Salon 2', location: 'Main Salon', capacity: 8 },
      { id: 't26', name: 'Chef Table', location: 'Kitchen', capacity: 4 },
    ],
  },
  {
    id: '6',
    name: 'Seoul Kitchen',
    cuisine: 'Korean',
    description: 'Modern Korean BBQ and traditional Korean dishes in a lively social dining atmosphere.',
    address: '987 West 32nd Street, New York, NY 10001',
    phone: '+1 (212) 555-0606',
    email: 'info@seoulkitchen.com',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    rating: 4.4,
    reviewCount: 278,
    priceRange: '$$',
    openingHours: '11:00 AM - 12:00 AM',
    tables: [
      { id: 't27', name: 'BBQ Table 1', location: 'BBQ Section', capacity: 4 },
      { id: 't28', name: 'BBQ Table 2', location: 'BBQ Section', capacity: 6 },
      { id: 't29', name: 'Regular Table 1', location: 'Main Floor', capacity: 2 },
      { id: 't30', name: 'Regular Table 2', location: 'Main Floor', capacity: 4 },
    ],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    restaurantId: '1',
    userId: 'u1',
    userName: 'Sarah M.',
    userAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=100&q=80',
    rating: 5,
    comment: 'Absolutely amazing food! The tacos al pastor were out of this world. Will definitely come back.',
    date: '2024-06-15',
  },
  {
    id: 'r2',
    restaurantId: '1',
    userId: 'u2',
    userName: 'James T.',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    rating: 4,
    comment: 'Great atmosphere and delicious food. The guacamole is freshly made tableside!',
    date: '2024-06-10',
  },
  {
    id: 'r3',
    restaurantId: '2',
    userId: 'u3',
    userName: 'Emily K.',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    rating: 5,
    comment: 'Best omakase in the city! Chef Tanaka is a true artist. Every dish was a masterpiece.',
    date: '2024-06-18',
  },
  {
    id: 'r4',
    restaurantId: '2',
    userId: 'u4',
    userName: 'Michael R.',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    rating: 5,
    comment: 'Incredible sushi! The fish is so fresh and the presentation is beautiful.',
    date: '2024-06-12',
  },
  {
    id: 'r5',
    restaurantId: '3',
    userId: 'u5',
    userName: 'Anna L.',
    userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80',
    rating: 4,
    comment: 'The pasta carbonara was perfectly creamy. Great wine selection too!',
    date: '2024-06-20',
  },
  {
    id: 'r6',
    restaurantId: '4',
    userId: 'u6',
    userName: 'David P.',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    rating: 5,
    comment: 'The butter chicken is the best I have ever had outside of India. Absolutely divine!',
    date: '2024-06-17',
  },
  {
    id: 'r7',
    restaurantId: '5',
    userId: 'u7',
    userName: 'Claire D.',
    userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80',
    rating: 5,
    comment: 'A true Parisian experience in New York! The duck confit is magnificent.',
    date: '2024-06-14',
  },
  {
    id: 'r8',
    restaurantId: '6',
    userId: 'u8',
    userName: 'Kevin J.',
    userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80',
    rating: 4,
    comment: 'Amazing Korean BBQ! The marinated short ribs are incredible. Fun group dining experience.',
    date: '2024-06-19',
  },
];

export const generateTimeSlots = (restaurantId: string, date: string): TimeSlot[] => {
  const times = ['12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30'];
  return times.map((time, index) => ({
    id: `ts-${restaurantId}-${date}-${index}`,
    restaurantId,
    date,
    time,
    available: Math.random() > 0.3,
    tableIds: ['t1', 't2', 't3'],
  }));
};

export const bookings: Booking[] = [
  {
    id: 'b1',
    restaurantId: '1',
    userId: 'u1',
    userName: 'Sarah Mitchell',
    userEmail: 'sarah@example.com',
    tableId: 't1',
    tableName: 'Window Table 1',
    tableLocation: 'Window',
    date: new Date().toISOString().split('T')[0],
    time: '19:00',
    partySize: 2,
    status: 'confirmed',
    allergies: ['nuts', 'dairy'],
    specialRequests: 'Anniversary dinner, please prepare a surprise dessert',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b2',
    restaurantId: '1',
    userId: 'u2',
    userName: 'James Thompson',
    userEmail: 'james@example.com',
    tableId: 't3',
    tableName: 'Patio Table 1',
    tableLocation: 'Patio',
    date: new Date().toISOString().split('T')[0],
    time: '19:30',
    partySize: 4,
    status: 'confirmed',
    allergies: ['gluten'],
    specialRequests: '',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b3',
    restaurantId: '1',
    userId: 'u3',
    userName: 'Emily Chen',
    userEmail: 'emily@example.com',
    tableId: 't5',
    tableName: 'Main Floor Table 1',
    tableLocation: 'Main Floor',
    date: new Date().toISOString().split('T')[0],
    time: '20:00',
    partySize: 3,
    status: 'pending',
    allergies: [],
    specialRequests: 'High chair needed for toddler',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b4',
    restaurantId: '1',
    userId: 'u4',
    userName: 'Michael Rodriguez',
    userEmail: 'michael@example.com',
    tableId: 't2',
    tableName: 'Window Table 2',
    tableLocation: 'Window',
    date: new Date().toISOString().split('T')[0],
    time: '18:30',
    partySize: 4,
    status: 'confirmed',
    allergies: ['shellfish', 'soy'],
    specialRequests: '',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b5',
    restaurantId: '1',
    userId: 'u5',
    userName: 'Anna Lee',
    userEmail: 'anna@example.com',
    tableId: 't6',
    tableName: 'Main Floor Table 2',
    tableLocation: 'Main Floor',
    date: new Date().toISOString().split('T')[0],
    time: '21:00',
    partySize: 8,
    status: 'confirmed',
    allergies: ['dairy'],
    specialRequests: 'Birthday celebration',
    createdAt: new Date().toISOString(),
  },
];
